import { Pipe, PipeTransform, inject } from '@angular/core';
import { TranslateService } from '@ngx-translate/core';

@Pipe({ name: 'statusLabel', standalone: true, pure: false })
export class StatusLabelPipe implements PipeTransform {
  private translate = inject(TranslateService);

  private keyMap: Record<string, string> = {
    'DRAFT': 'STATUS.DRAFT',
    'DOCUMENTATION_COMPLETE': 'STATUS.DOCUMENTATION_COMPLETE',
    'IN_REVIEW': 'STATUS.IN_REVIEW',
    'PENDING_CORRECTION': 'STATUS.PENDING_CORRECTION',
    'PRELIQUIDATION_REVIEW': 'STATUS.PRELIQUIDATION_REVIEW',
    'ANALYST_ASSIGNED': 'STATUS.ANALYST_ASSIGNED',
    'DECLARATION_IN_PROGRESS': 'STATUS.DECLARATION_IN_PROGRESS',
    'SUBMITTED_TO_CUSTOMS': 'STATUS.SUBMITTED_TO_CUSTOMS',
    'VALUATION_REVIEW': 'STATUS.VALUATION_REVIEW',
    'PAYMENT_PREPARATION': 'STATUS.PAYMENT_PREPARATION',
    'IN_TRANSIT': 'STATUS.IN_TRANSIT',
    'CLOSED': 'STATUS.CLOSED',
    'CANCELLED': 'STATUS.CANCELLED',
    'BL': 'DOCUMENT_TYPES.BL',
    'COMMERCIAL_INVOICE': 'DOCUMENT_TYPES.COMMERCIAL_INVOICE',
    'PACKING_LIST': 'DOCUMENT_TYPES.PACKING_LIST',
    'CERTIFICATE': 'DOCUMENT_TYPES.CERTIFICATE',
    'OTHER': 'DOCUMENT_TYPES.OTHER',
    'MARITIME': 'TRANSPORT_MODES.MARITIME',
    'AIR': 'TRANSPORT_MODES.AIR',
    'CATEGORY_1': 'OPERATION_CATEGORIES.CATEGORY_1',
    'CATEGORY_2': 'OPERATION_CATEGORIES.CATEGORY_2',
    'CATEGORY_3': 'OPERATION_CATEGORIES.CATEGORY_3',
    'PRELIMINARY': 'DECLARATION_TYPES.PRELIMINARY',
    'FINAL': 'DECLARATION_TYPES.FINAL',
    'MATCH': 'CROSSING.MATCH',
    'DISCREPANCY': 'CROSSING.DISCREPANCY',
    'RESOLVED': 'CROSSING.RESOLVED',
    'INACTIVITY_48H': 'ALERT_TYPES.INACTIVITY_48H',
    'DEADLINE_APPROACHING': 'ALERT_TYPES.DEADLINE_APPROACHING',
    'MISSING_CRITICAL_DOCUMENT': 'ALERT_TYPES.MISSING_CRITICAL_DOCUMENT',
    'BL_UNAVAILABLE': 'ALERT_TYPES.BL_UNAVAILABLE',
    'ACTIVE': 'ALERT_STATUS.ACTIVE',
    'ACKNOWLEDGED': 'ALERT_STATUS.ACKNOWLEDGED'
  };

  transform(value: string): string {
    const key = this.keyMap[value];
    return key ? this.translate.instant(key) : value;
  }
}
