package com.janus.document.domain.model;

public enum DocumentType {
    BL,
    COMMERCIAL_INVOICE,
    PACKING_LIST,
    CERTIFICATE,
    PERMIT_CERTIFICATE,
    LOCAL_CHARGES_RECEIPT,
    RECEPTION_RECEIPT,
    LIQUIDATION_DOCUMENT,
    PAYMENT_RECEIPT,
    AGENCY_INVOICE,
    INITIAL_DECLARATION,
    FINAL_DECLARATION,
    OTHER
}
